### ISSUE TITLE
[FEATURE] Do not clear console when running with --no-ui

### ISSUE THREAD

**Issue by NTFSvolume** [jbsparrow/CyberDropDownloader#106]
I use a custom script to run multiple CDL commands in sequence with different configs, urls, output folder, etc. However, every new instance of CDL clear the console when it finishes, losing the the summary of the previous run. When using the same log file for all the runs, the file gets overwritten.

Using different logs files works but them you have to check them all individually. 

By disabling the console clear you will be able to see the summary of the previous runs by just scrolling up in the console buffer.

**Comment by jbsparrow** [comment]
Each config has it's own log folder, and you can use the `discord_webhook_url` parameter to have the logs sent to a webhook at the end of each run.

https://script-ware.gitbook.io/cyberdrop-dl/reference/configuration-options/settings#logs

**Comment by NTFSvolume** [comment]
I use a different log folder for each run, but that still requires you to check each log file individually. 

I will look into setting up a webhook. However, I still think this feature is worth implementing, just for convenience.
