### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by DrWifeGone** [jbsparrow/CyberDropDownloader#120]
Hey everyone, I am having a problem where the CyberDrop does not scraping any of links and shows finished download terminal. Could any help me about it? It was working fine last week now its broken. Is there any relationship with a lot of URLs?

[downloader.log](https://github.com/user-attachments/files/17095835/downloader.log)

![Screenshot (63)](https://github.com/user-attachments/assets/f270405e-e6e1-4fb5-962f-817cf3cd0dfc)

 - OS: Windows 11
 - Cyberdrop Downloader Version 5.3.41

**Comment by NTFSvolume** [comment]
Logs says you are running v5.6.32 and all URLs are from SimpCity. Support for SimpCity has been removed [since PR#117](https://github.com/jbsparrow/CyberDropDownloader/pull/117)

[You can read why here](https://script-ware.gitbook.io/cyberdrop-dl/simpcity-support-dropped)
