### ISSUE TITLE
[FEATURE] Group downloads in folders via the text file

### ISSUE THREAD

**Issue by eldark** [jbsparrow/CyberDropDownloader#133]
**Is your feature request related to a problem? Please describe.**
Due to the dropping of Simpcity support, I have started manually scrapping (via Javascript) content of threads, and then pasting these urls to the urls text file. The problem is that there's no way (at least, I haven't found one) to automate sorting each group of links. I need to add these one group at a time, download, rename folder, repeat.

**Describe the solution you'd like**
It would be great to have some reserved words in the text file that could, somehow, group downloads in a sub-folder. Something like this:
```
["Group 1"]
https://some.host.com/link-1
https://some.host.com/link-2
https://some.host.com/link-3
["Group 2"]
https://some.host.com/link-4
https://some.host.com/link-5
https://some.host.com/link-6
...
```
Then, `cyberdrop-dl-patched` would move files like so:

```
path/to/downloads/Group 1/file-1
path/to/downloads/Group 1/file-2
path/to/downloads/Group 1/file-3
path/to/downloads/Group 2/file-1
path/to/downloads/Group 2/file-2
path/to/downloads/Group 2/file-3
```

Opening / closing tags are OK too.

**Additional context**
I think I described the feature clear enough, but can provide additional info if needed!

**Comment by jbsparrow** [comment]
This feature was added in PR #119, you can use `---` or `===` as the prefix for a title. More details can be found within the PR :)
