### ISSUE TITLE
[FEATURE][FIX] Cyberdrop.me DDOS-Guard

### ISSUE THREAD

**Issue by sintaxx** [jbsparrow/CyberDropDownloader#154]
**Is your feature request related to a problem? Please describe.**
Related to problem. Cyberdrop.me causes failures due to DDOS-Guard.

**Describe the solution you'd like**
Implement my solution to fix the cyberdrop.me crawler/downloader to bypass ddos-guard

**Additional context**
I'm not too good at using github but I was messing around with python and copilot and was able to modify the cyberdrop crawler code and fix downloading but couldn't figure out how to scrape the album name.

https://k1.cyberdrop.ch/api/file/d/{filename_part}?token=null

setting the domain to k1.cyberdrop.ch and setting token to null for each file should work.

I had to dump a filename/link list from album and then once you paste all of the file links into URLs.txt the downloader will work.

I forked the CyberDrop-DL code and edited the file if anyone wants to use it as a reference to implement the modifications.

**Comment by jbsparrow** [comment]
You can open a fork to implement the fix. Make sure you're forking from my repository and not Jules'.

**Comment by sintaxx** [comment]
> You can open a fork to implement the fix. Make sure you're forking from my repository and not Jules'.

Since it seems to get patched too quickly as per BigYellowTaco, I will hold off on a public patch, unless you have a way to obfuscate the code used to bypass ddos-guard.

**Comment by jbsparrow** [comment]
Cyberdrop-DL will always remain an open-source project and we will never obfuscate code. It's best that you keep your fixes private.
