### ISSUE TITLE
[BUG] Bunkr 404 on all links as of today

### ISSUE THREAD

**Issue by Kenneth-Rosenstroem** [jbsparrow/CyberDropDownloader#176]
**Describe the bug**

404 status no matter the link. See attached picture.

Bunkr changed their design this morning, as well as everything else, I guess. The result is that CyberDrop gives a status 404 on all links.

Example link: 
https://bunkr.ax/a/aSVb9hmd

Screenshot: 

![2024-10-19_15h02_10](https://github.com/user-attachments/assets/23b2b8f5-2c14-4284-b077-b6ce958bbc93)

Logfile:
[downloader.log](https://github.com/user-attachments/files/17445065/downloader.log)

**Comment by crazydavebacon** [comment]
same here, seems they changed something again. Happens on Jdownloader also.

**Comment by NTFSvolume** [comment]
> looks like #178 fixes some domains, but the following links still return 404 in CDL although they do work in browser.
> 
> ```
> https://bunkrrr.org/a/mzK7ZLmI
> https://bunkrrr.org/a/U8kDLVkQ
> https://cyberdrop.me/Ap%20best%20deptroath-GY1soyG8.mp4
> https://cyberdrop.me/Ap%20mouth%20cumshot-nSZnydIJ.mp4
> ```

both bunkr links works with #178 branch. Keep in mind that the merge was approved but has not been released. You are probably using the current version.

cyberdrop links don't work cause CDL does not support that format of link, only `https://cyberdrop.me/f/<FILE_ID>` or `https://cyberdrop.me/a/<ALBUM_ID>`. Support for it can not be implemented right now cause they require bypassing DDOS guard to solve.

**Comment by baccccccc** [comment]
> both bunkr links works with #178 branch. Keep in mind that the merge was approved but has not been released. You are probably using the current version.

thanks for clarification. I did indeed just clone `master`. Did not pay attention to branch in that PR, my bad.

> cyberdrop links don't work cause CDL does not support that format of link, only `https://cyberdrop.me/f/<FILE_ID>` or `https://cyberdrop.me/a/<ALBUM_ID>`. Support for it can not be implemented right now cause they require bypassing DDOS guard to solve.

that's unfortunate. We could, at least partially, address DDoS-Guard by using FlareSolverr in interactive mode. It's a PITA but still better than no solution at all.
