### ISSUE TITLE
[FEATURE]Please support nekhouse.su.

### ISSUE THREAD

**Issue by mikashina** [jbsparrow/CyberDropDownloader#184]
Please support nekhouse.su.

**Comment by jbsparrow** [comment]
I can't find the website. Has their domain changed?

**Comment by NTFSvolume** [comment]
URL is https://nekohouse.su

It's `coomer`/`kemono` but for fantia/fanbox/subscribestar. They don't have API support yet.

On their group was mentioned that adding API support is a low priority right now. A new crawler would need to written from scratch cause the `kemono` code can not be reused.

**Comment by jbsparrow** [comment]
I'll add support for it later today. Unfortunate that they don't have an API.

**Comment by mikashina** [comment]
Thank you for being the first to respond so quickly.

Now, I tried the code you mentioned in your pull request, but I got the following error.

I would appreciate it if you could help me with debugging.

`                    INFO     Scrape Starting: https://nekohouse.su/fantia/user/380962                                                           utilities.py:112
[10/29/24 06:48:31] ERROR    Scrape Failed: https://nekohouse.su/fantia/user/380962/post/247783 ('NoneType' object has no attribute 'text')     utilities.py:112
                             ╭────────────────────────────────────── Traceback (most recent call last) ───────────────────────────────────────╮                 
                             │ C:\Users\hoge\AppData\Local\Programs\Python\Python311\Lib\site-packages\cyberdrop_dl\utils\utilities.py:71 in │                 
                             │ wrapper                                                                                                        │                 
                             │                                                                                                                │                 
                             │    68 │   │   link = args[0] if isinstance(args[0], URL) else args[0].url                                      │                 
                             │    69 │   │                                                                                                    │                 
                             │    70 │   │   try:                                                                                             │                 
                             │ ❱  71 │   │   │   return await func(self, *args, **kwargs)                                                     │                 
                             │    72 │   │   except NoExtensionFailure:                                                                       │                 
                             │    73 │   │   │   await log(f"Scrape Failed: {link} (No File Extension)", 40)                                  │                 
                             │    74 │   │   │   await self.manager.log_manager.write_scrape_error_log(link, " No File                        │                 
                             │       Extension")                                                                                              │                 
                             │                                                                                                                │                 
                             │ C:\Users\hoge\AppData\Local\Programs\Python\Python311\Lib\site-packages\cyberdrop_dl\scraper\crawlers\nekohou │                 
                             │ se_crawler.py:102 in get_post_content                                                                          │                 
                             │                                                                                                                │                 
                             │    99 │   │   │   │   "id": post,                                                                              │                 
                             │   100 │   │   │   │   "user": user,                                                                            │                 
                             │   101 │   │   │   │   "service": service,                                                                      │                 
                             │ ❱ 102 │   │   │   │   "title": soup.select_one(self.post_title_selector).text.strip(),                         │                 
                             │   103 │   │   │   │   "content": soup.select_one(self.post_content_selector).text.strip(),                     │                 
                             │   104 │   │   │   │   "user_str":                                                                              │                 
                             │       soup.select_one(self.post_author_username_selector).text.strip(),                                        │                 
                             │   105 │   │   │   │   "published": soup.select_one(self.post_timestamp_selector).text.strip(),                 │                 
                             ╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯                 
                             AttributeError: 'NoneType' object has no attribute 'text'                                                                          
[10/29/24 06:48:32] ERROR    Scrape Failed: https://nekohouse.su/fantia/user/380962/post/247784 ('NoneType' object has no attribute 'text')     utilities.py:112
                             ╭────────────────────────────────────── Traceback (most recent call last) ───────────────────────────────────────╮                 
                             │ C:\Users\hoge\AppData\Local\Programs\Python\Python311\Lib\site-packages\cyberdrop_dl\utils\utilities.py:71 in │                 
                             │ wrapper                                                                                                        │                 
                             │                                                                                                                │                 
                             │    68 │   │   link = args[0] if isinstance(args[0], URL) else args[0].url                                      │                 
                             │    69 │   │                                                                                                    │                 
                             │    70 │   │   try:                                                                                             │                 
                             │ ❱  71 │   │   │   return await func(self, *args, **kwargs)                                                     │                 
                             │    72 │   │   except NoExtensionFailure:                                                                       │                 
                             │    73 │   │   │   await log(f"Scrape Failed: {link} (No File Extension)", 40)                                  │                 
                             │    74 │   │   │   await self.manager.log_manager.write_scrape_error_log(link, " No File                        │                 
                             │       Extension")                                                                                              │                 
                             │                                                                                                                │                 
                             │ C:\Users\hoge\AppData\Local\Programs\Python\Python311\Lib\site-packages\cyberdrop_dl\scraper\crawlers\nekohou │                 
                             │ se_crawler.py:102 in get_post_content                                                                          │                 
                             │                                                                                                                │                 
                             │    99 │   │   │   │   "id": post,                                                                              │                 
                             │   100 │   │   │   │   "user": user,                                                                            │                 
                             │   101 │   │   │   │   "service": service,                                                                      │                 
                             │ ❱ 102 │   │   │   │   "title": soup.select_one(self.post_title_selector).text.strip(),                         │                 
                             │   103 │   │   │   │   "content": soup.select_one(self.post_content_selector).text.strip(),                     │                 
                             │   104 │   │   │   │   "user_str":                                                                              │                 
                             │       soup.select_one(self.post_author_username_selector).text.strip(),                                        │                 
                             │   105 │   │   │   │   "published": soup.select_one(self.post_timestamp_selector).text.strip(),                 │                 
                             ╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯                 
                             AttributeError: 'NoneType' object has no attribute 'text'                                                                          
[10/29/24 06:48:42] INFO     Scrape Finished: https://nekohouse.su/fantia/user/380962                                                           utilities.py:112
                    INFO     Scrape Starting: https://nekohouse.su/fantia_products/user/191767                                                  utilities.py:112
[10/29/24 06:48:45] ERROR    Scrape Failed: https://nekohouse.su/fantia_products/user/191767/post/229425 (time data '' does not match format    utilities.py:112
                             '%Y-%m-%d %H:%M:%S.%f')                                                                                                            
                             ╭────────────────────────────────────── Traceback (most recent call last) ───────────────────────────────────────╮                 
                             │ C:\Users\hoge\AppData\Local\Programs\Python\Python311\Lib\site-packages\cyberdrop_dl\scraper\crawlers\nekohou │                 
                             │ se_crawler.py:168 in parse_datetime                                                                            │                 
                             │                                                                                                                │                 
                             │   165 │   async def parse_datetime(self, date: str) -> int:                                                    │                 
                             │   166 │   │   """Parses a datetime string into a unix timestamp"""                                             │                 
                             │   167 │   │   try:                                                                                             │                 
                             │ ❱ 168 │   │   │   date = datetime.datetime.strptime(date, "%Y-%m-%d %H:%M:%S")                                 │                 
                             │   169 │   │   except ValueError:                                                                               │                 
                             │   170 │   │   │   date = datetime.datetime.strptime(date, "%Y-%m-%d %H:%M:%S.%f")                              │                 
                             │   171 │   │   return calendar.timegm(date.timetuple())                                                         │                 
                             │                                                                                                                │                 
                             │ C:\Users\hoge\AppData\Local\Programs\Python\Python311\Lib\_strptime.py:568 in _strptime_datetime              │                 
                             │                                                                                                                │                 
                             │   565 def _strptime_datetime(cls, data_string, format="%a %b %d %H:%M:%S %Y"):                                 │                 
                             │   566 │   """Return a class cls instance based on the input string and the                                     │                 
                             │   567 │   format string."""                                                                                    │                 
                             │ ❱ 568 │   tt, fraction, gmtoff_fraction = _strptime(data_string, format)                                       │                 
                             │   569 │   tzname, gmtoff = tt[-2:]                                                                             │                 
                             │   570 │   args = tt[:6] + (fraction,)                                                                          │                 
                             │   571 │   if gmtoff is not None:                                                                               │                 
                             │                                                                                                                │                 
                             │ C:\Users\hoge\AppData\Local\Programs\Python\Python311\Lib\_strptime.py:349 in _strptime                       │                 
                             │                                                                                                                │                 
                             │   346 │   │   │   _regex_cache[format] = format_regex                                                          │                 
                             │   347 │   found = format_regex.match(data_string)                                                              │                 
                             │   348 │   if not found:                                                                                        │                 
                             │ ❱ 349 │   │   raise ValueError("time data %r does not match format %r" %                                       │                 
                             │   350 │   │   │   │   │   │    (data_string, format))                                                          │                 
                             │   351 │   if len(data_string) != found.end():                                                                  │                 
                             │   352 │   │   raise ValueError("unconverted data remains: %s" %                                                │                 
                             ╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯                 
                             ValueError: time data '' does not match format '%Y-%m-%d %H:%M:%S'                                                                 
                                                                                                                                                                
                             During handling of the above exception, another exception occurred:                                                                
                                                                                                                                                                
                             ╭────────────────────────────────────── Traceback (most recent call last) ───────────────────────────────────────╮                 
                             │ C:\Users\hoge\AppData\Local\Programs\Python\Python311\Lib\site-packages\cyberdrop_dl\utils\utilities.py:71 in │                 
                             │ wrapper                                                                                                        │                 
                             │                                                                                                                │                 
                             │    68 │   │   link = args[0] if isinstance(args[0], URL) else args[0].url                                      │                 
                             │    69 │   │                                                                                                    │                 
                             │    70 │   │   try:                                                                                             │                 
                             │ ❱  71 │   │   │   return await func(self, *args, **kwargs)                                                     │                 
                             │    72 │   │   except NoExtensionFailure:                                                                       │                 
                             │    73 │   │   │   await log(f"Scrape Failed: {link} (No File Extension)", 40)                                  │                 
                             │    74 │   │   │   await self.manager.log_manager.write_scrape_error_log(link, " No File                        │                 
                             │       Extension")                                                                                              │                 
                             │                                                                                                                │                 
                             │ C:\Users\hoge\AppData\Local\Programs\Python\Python311\Lib\site-packages\cyberdrop_dl\scraper\crawlers\nekohou │                 
                             │ se_crawler.py:152 in handle_post_content                                                                       │                 
                             │                                                                                                                │                 
                             │   149 │   │   │   await self.create_new_scrape_item(link, scrape_item, user_str, post_title,                   │                 
                             │       post_id, date)                                                                                           │                 
                             │   150 │   │                                                                                                    │                 
                             │   151 │   │   for file in post['attachments']:                                                                 │                 
                             │ ❱ 152 │   │   │   await handle_file(file)                                                                      │                 
                             │   153 │                                                                                                        │                 
                             │   154 │   @error_handling_wrapper                                                                              │                 
                             │   155 │   async def handle_direct_link(self, scrape_item: ScrapeItem) -> None:                                 │                 
                             │                                                                                                                │                 
                             │ C:\Users\hoge\AppData\Local\Programs\Python\Python311\Lib\site-packages\cyberdrop_dl\scraper\crawlers\nekohou │                 
                             │ se_crawler.py:149 in handle_file                                                                               │                 
                             │                                                                                                                │                 
                             │   146 │   │   async def handle_file(file_obj):                                                                 │                 
                             │   147 │   │   │   link = self.primary_base_domain / file_obj['path']                                           │                 
                             │   148 │   │   │   link = link.with_query({"f": file_obj['name']})                                              │                 
                             │ ❱ 149 │   │   │   await self.create_new_scrape_item(link, scrape_item, user_str, post_title,                   │                 
                             │       post_id, date)                                                                                           │                 
                             │   150 │   │                                                                                                    │                 
                             │   151 │   │   for file in post['attachments']:                                                                 │                 
                             │   152 │   │   │   await handle_file(file)                                                                      │                 
                             │                                                                                                                │                 
                             │ C:\Users\hoge\AppData\Local\Programs\Python\Python311\Lib\site-packages\cyberdrop_dl\scraper\crawlers\nekohou │                 
                             │ se_crawler.py:232 in create_new_scrape_item                                                                    │                 
                             │                                                                                                                │                 
                             │   229 │   │                                                                                                    │                 
                             │   230 │   │   new_title = await self.create_title(user, None, None)                                            │                 
                             │   231 │   │   new_scrape_item = await self.create_scrape_item(old_scrape_item, link,                           │                 
                             │       new_title, True, None,                                                                                   │                 
                             │ ❱ 232 │   │   │   │   │   │   │   │   │   │   │   │   │   │   await self.parse_datetime(date),                 │                 
                             │       add_parent = add_parent)                                                                                 │                 
                             │   233 │   │   await new_scrape_item.add_to_parent_title(post_title)                                            │                 
                             │   234 │   │   self.manager.task_group.create_task(self.run(new_scrape_item))                                   │                 
                             │   235                                                                                                          │                 
                             │                                                                                                                │                 
                             │ C:\Users\hoge\AppData\Local\Programs\Python\Python311\Lib\site-packages\cyberdrop_dl\scraper\crawlers\nekohou │                 
                             │ se_crawler.py:170 in parse_datetime                                                                            │                 
                             │                                                                                                                │                 
                             │   167 │   │   try:                                                                                             │                 
                             │   168 │   │   │   date = datetime.datetime.strptime(date, "%Y-%m-%d %H:%M:%S")                                 │                 
                             │   169 │   │   except ValueError:                                                                               │                 
                             │ ❱ 170 │   │   │   date = datetime.datetime.strptime(date, "%Y-%m-%d %H:%M:%S.%f")                              │                 
                             │   171 │   │   return calendar.timegm(date.timetuple())                                                         │                 
                             │   172 │                                                                                                        │                 
                             │   173 │   @error_handling_wrapper                                                                              │                 
                             │                                                                                                                │                 
                             │ C:\Users\hoge\AppData\Local\Programs\Python\Python311\Lib\_strptime.py:568 in _strptime_datetime              │                 
                             │                                                                                                                │                 
                             │   565 def _strptime_datetime(cls, data_string, format="%a %b %d %H:%M:%S %Y"):                                 │                 
                             │   566 │   """Return a class cls instance based on the input string and the                                     │                 
                             │   567 │   format string."""                                                                                    │                 
                             │ ❱ 568 │   tt, fraction, gmtoff_fraction = _strptime(data_string, format)                                       │                 
                             │   569 │   tzname, gmtoff = tt[-2:]                                                                             │                 
                             │   570 │   args = tt[:6] + (fraction,)                                                                          │                 
                             │   571 │   if gmtoff is not None:                                                                               │                 
                             │                                                                                                                │                 
                             │ C:\Users\hoge\AppData\Local\Programs\Python\Python311\Lib\_strptime.py:349 in _strptime                       │                 
                             │                                                                                                                │                 
                             │   346 │   │   │   _regex_cache[format] = format_regex                                                          │                 
                             │   347 │   found = format_regex.match(data_string)                                                              │                 
                             │   348 │   if not found:                                                                                        │                 
                             │ ❱ 349 │   │   raise ValueError("time data %r does not match format %r" %                                       │                 
                             │   350 │   │   │   │   │   │    (data_string, format))                                                          │                 
                             │   351 │   if len(data_string) != found.end():                                                                  │                 
                             │   352 │   │   raise ValueError("unconverted data remains: %s" %                                                │                 
                             ╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯                 
                             ValueError: time data '' does not match format '%Y-%m-%d %H:%M:%S.%f'                                                              
[10/29/24 06:48:46] INFO     Scrape Finished: https://nekohouse.su/fantia_products/user/191767                                                  utilities.py:112
                    INFO     Scrape Starting: https://nekohouse.su/fantia/user/39009                                                            utilities.py:112
[10/29/24 06:49:19] ERROR    Scrape Failed: https://nekohouse.su/fantia/user/39009/post/2811470 ('NoneType' object has no attribute 'text')     utilities.py:112
                             ╭────────────────────────────────────── Traceback (most recent call last) ───────────────────────────────────────╮                 
                             │ C:\Users\hoge\AppData\Local\Programs\Python\Python311\Lib\site-packages\cyberdrop_dl\utils\utilities.py:71 in │                 
                             │ wrapper                                                                                                        │                 
                             │                                                                                                                │                 
                             │    68 │   │   link = args[0] if isinstance(args[0], URL) else args[0].url                                      │                 
                             │    69 │   │                                                                                                    │                 
                             │    70 │   │   try:                                                                                             │                 
                             │ ❱  71 │   │   │   return await func(self, *args, **kwargs)                                                     │                 
                             │    72 │   │   except NoExtensionFailure:                                                                       │                 
                             │    73 │   │   │   await log(f"Scrape Failed: {link} (No File Extension)", 40)                                  │                 
                             │    74 │   │   │   await self.manager.log_manager.write_scrape_error_log(link, " No File                        │                 
                             │       Extension")                                                                                              │                 
                             │                                                                                                                │                 
                             │ C:\Users\hoge\AppData\Local\Programs\Python\Python311\Lib\site-packages\cyberdrop_dl\scraper\crawlers\nekohou │                 
                             │ se_crawler.py:103 in get_post_content                                                                          │                 
                             │                                                                                                                │                 
                             │   100 │   │   │   │   "user": user,                                                                            │                 
                             │   101 │   │   │   │   "service": service,                                                                      │                 
                             │   102 │   │   │   │   "title": soup.select_one(self.post_title_selector).text.strip(),                         │                 
                             │ ❱ 103 │   │   │   │   "content": soup.select_one(self.post_content_selector).text.strip(),                     │                 
                             │   104 │   │   │   │   "user_str":                                                                              │                 
                             │       soup.select_one(self.post_author_username_selector).text.strip(),                                        │                 
                             │   105 │   │   │   │   "published": soup.select_one(self.post_timestamp_selector).text.strip(),                 │                 
                             │   106 │   │   │   │   "file": [],                                                                              │                 
                             ╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯                 
                             AttributeError: 'NoneType' object has no attribute 'text'   `
