### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Mrimpossiblemk** [jbsparrow/CyberDropDownloader#195]
its not supporting download from BUNKR anymore, 
the site itself working fine and we are able to download the file manually
but when it comes to cyberdrop,  it show "SCRAPE FAILURE"

**Screenshots**
![Screenshot 2024-10-23 140533](https://github.com/user-attachments/assets/ed1c06c0-a46b-4aee-ae1e-9a86633d597a)

**Setup Information**
 - OS: windows 10
 - Cyberdrop Downloader Version  (V5.3.31)

**Comment by NTFSvolume** [comment]
You are using a version that is over 4 months old. Update

**Comment by Mrimpossiblemk** [comment]
@NTFSvolume  can you share me the link of new,, please i am noob

**Comment by Mrimpossiblemk** [comment]
thanks man @NTFSvolume  i thought it automatically updates every time  i open
