### ISSUE TITLE
[BUG] "Invalid Content Received" on dosyaupload

### ISSUE THREAD

**Issue by baccccccc** [jbsparrow/CyberDropDownloader#203]
Honestly, this is the first time I see this website and I'm surprised it's even supported.

```
https://www.dosyaupload.com/2NGjt/AP-1-YLARomht.mp4
```

However, currently this download fails with "Invalid Content Received". 

```
                    INFO     Download Starting: https://www.dosyaupload.com/2NGjt/AP-1-YLARomht.mp4                                             utilities.py:112
[10/23/24 18:11:16] ERROR    Download Failed: https://www.dosyaupload.com/2NGjt/AP-1-YLARomht.mp4 received Invalid Content                      utilities.py:112
                    ERROR    Received text/html; charset=UTF-8, was expecting other                                                             utilities.py:112
                    INFO     Download Finished: https://www.dosyaupload.com/2NGjt/AP-1-YLARomht.mp4                                             utilities.py:112
```

I'm not sure why it's unexpected. Seems to work fine in the browser (albeit a bit slow.)

**Comment by jbsparrow** [comment]
Dosyaupload isn't supported, but because the URL implies that it points to a file, CDL tries to download the mp4 file that is being referenced. I can't reach the website right now, but based on the error it looks like it's returning a webpage with a viewer or something of that sort and not an mp4 file like the URL implies it would, causing an error.

**Comment by baccccccc** [comment]
interesting. Well, it makes sense that if the site is not supported, CDL is doing reasonable best effort go grab the file, and it's also unsurprising that it fails. However, in order to reduce confusion, can we make error handling better? E.g., state explicitly that the website is not supported, and there's no expectation it will work.

**Comment by jbsparrow** [comment]
Definitely! I'm surprised that we didn't have this functionality in the first place.
