### ISSUE TITLE
Miscellaneous logging improvements (was: password protected links are not included to Scrape_Error_URLs.csv)

### ISSUE THREAD

**Issue by baccccccc** [jbsparrow/CyberDropDownloader#210]
Once the script finishes, I receive the following output.

```
Scrape Failures:
Unsupported URLs, Sent to Jdownloader: 0
Unsupported URLs, Skipped: 139
Unsupported URLs, Total: 139
Scrape Failures (404 HTTP Status): 19
Scrape Failures (Password Protected): 19
```

Since those are scrape failures, I'd expect to find all of these links in `Scrape_Error_URLs.csv`. Indeed, I do see 19 entries for 404 error there, but none for "password protected" links.

(After reviewing the `downloader.log`, all these links are on cyberfile.me, so maybe this issue is specific to that domain.)

**Comment by baccccccc** [comment]
crap, I just remembered [it was me](https://github.com/Jules-WinnfieldX/CyberDropDownloader/issues/867) who requested these links to go into `Unsupported_URLs`. Ok. I stand by my original request. After all, the rational was that I can download them manually once, and stop bothering. And this is what I typically do with `Unsupported_URLs`. (And I hope that converting it to CSV will help me stop bothering even better.)

but maybe the count should not be in the `Scrape Failures:` section of the output?

**Comment by jbsparrow** [comment]
I think the output should remain in the scrape failures because it the host is supported, but not that feature of the host.

This does bring up an issue though and that is why are we saving 404 errors. They are not something that the user will return to. The content will not be returning.

I might remove 404s from the scrape errors file. What do you think?

**Comment by baccccccc** [comment]
In general, I would expect that whatever is reported in `Scrape Failures:` section of the output, goes into `Scrape_Error_URLs.csv`. And likewise, whatever is reported in `Download Failures:` section, goes into `Download_Error_URLs.csv`. I think keeping those consistent will help analyzing the results.

so, given that `Unsupported_URLs` is yet another file, maybe we need as separate section in the output related to it.

also, I think keeping track of 404's and other errors makes sense. Let's not remove those. (Unless you find a new home for them.) In general, the more info the better. 

in general, I tend to think of it this way. Both `Download_Error_URLs.csv` and `Scrape_Error_URLs.csv` are about something CDL would normally handle, but it could not. Sometimes, restarting the app or reconfiguring it (e.g., to use FlareSolverr) could help with that. Sometimes it's permanent (like with 404s or 451s) but anywhay that's not something you could fix outside of CDL. As such, I do not often explore those details, unless I suspect that something went wrong.

`Unsupported_URLs` is not like this. When I see that, I know I'll have to investigate. Maybe I will download stuff manually, maybe not. But it's not something CDL would handle even in the best-case scenario. So, I should regularly revisit this file and see what's new there and what to do about it.

**Comment by NTFSvolume** [comment]
> `Unsupported_URLs` is not like this. When I see that, I know I'll have to investigate. Maybe I will download stuff manually, maybe not. But it's not something CDL would handle even in the best-case scenario. So, I should regularly revisit this file and see what's new there and what to do about it. (And password protected links fall into this category.)

CDL does support password protected URLs from a few hosts now. Cyberfile is one of them. By this logic, the URL should go to `Scrape_Error_URLs.csv`, not unsupported URLs

**Comment by ne0lith** [comment]
> I think the output should remain in the scrape failures because the host is supported, but not that feature of the host.
> 
> This does bring up an issue though and that is why are we saving 404 errors. They are not something that the user will return to. The content will not be returning.
> 
> I might remove 404s from the scrape errors file. What do you think?

Saving 404s is one of the only ways to know which urls to remove if you have a huge url list. Maybe give them their own log if they don't fit the methodology of scrape errors?

**Comment by jbsparrow** [comment]
That's true, I didn't think about that. I might think of a new place for them in the future but for now I will leave it as is.

**Comment by baccccccc** [comment]
> That's true, I didn't think about that. I might think of a new place for them in the future but for now I will leave it as is.

ok, this thread went a little sideways, with a lot of suggestions (good ones) to different problems.

I think we should separate them across a few different buckets.

1. Make sure everything counted as `Scrape Failures:` ends up in `Scrape_Error_URLs.csv` (and vice-versa).
2. Make sure everything counted as `Download Failures:` ends up in `Download_Error_URLs.csv` (and vice-versa).
3. Create a separate category in the output (similar to `Scrape Failures:` and `Download Failures:` for unsupported URLs and make sure it reflects the count of entries that go into `Unsupported_URLs.txt` (and vice-vera).
4. Figure out what `Unsupported_URLs` should look like long term (CSV or otherwise), continuing the discussion from old [#864](https://github.com/Jules-WinnfieldX/CyberDropDownloader/issues/864) and now #134.
5. Reshuffle some of the failure types between scrape failures, download failures and unsupported URLs, based on some of the proposals discussed in this thread (#210).
6. Anything else I forgot of?

**Comment by NTFSvolume** [comment]
If it's gonna change, I think is better to just switch to CSV for everything. But a proper CSV, with headers and quoted values if necessary.

`Scrape_Error_URLs` and `Download_Error_URLs`, will have 3 columns: `url`, `error`, `origin`

`origin` is the URL of the oldest parent, like the forum post where that URL came from

`Unsupported_URLs` will have 2 columns: `url` and `origin`

`Last_Forum_Post` may have 2 columns, `thread url` and `last post`. 

`last post` will just be the number. Or it could just be a single `url` column with the entire post URL (that's the current behaviour)

**Comment by baccccccc** [comment]
> `Unsupported_URLs` will have 2 columns: `url` and `origin`

I very much like your way of thinking, but please be mindful of the scenario I originally described in [#864](https://github.com/Jules-WinnfieldX/CyberDropDownloader/issues/864) when designing the new layout for `Unsupported_URLs`.

**Comment by NTFSvolume** [comment]
> I very much like your way of thinking, but please be mindful of the scenario I originally described in [#864](https://github.com/Jules-WinnfieldX/CyberDropDownloader/issues/864) when designing the new layout for `Unsupported_URLs`.

Keeping old values and only add new ones would be too complicated. It will require either reading the entire file every time you want to write something to it, to make sure is actually something new, or keep the records in a new internal database table.

You can use the `rotate_logs` option to create new logs instead of overwriting the old ones and them compare the diff between the old `Unsupported_URLs` and the new one
