### ISSUE TITLE
[BUG] Bunkr scrape issue

### ISSUE THREAD

**Issue by BSchul77** [jbsparrow/CyberDropDownloader#219]
So im not sure exactly what is going on. I was previously running V4, and I was encountering this same issue, so i upgraded to v5 and I am still having it. No matter what bunkr link/files I try to download, I constantly get a scrape failure. I tried going through the reading material for her, and it does state that "Quite simply, almost all of them you see will be HTTP Status codes. Such as: 404 - Not Found (dead link)" but the links are not dead.
Any help would be appreciated it

**Screenshots**
![image](https://github.com/user-attachments/assets/f81f74b2-869b-43d7-bf57-f3da4e128b29)
![Screenshot 2024-10-28 162255](https://github.com/user-attachments/assets/b7a870a6-30a8-42e7-aa2b-d64ff298eff5)

**Setup Information**
 - OS: W11
 - Cyberdrop Downloader Version: 5.7.0

**Downloader.log file**
[downloader.log](https://github.com/user-attachments/files/17549069/downloader.log)

**Additional context**

**Comment by NTFSvolume** [comment]
You are using v5.3.31 not v5.7. Update to v5.7

**Comment by BSchul77** [comment]
> You are using v5.3.31 not v5.7. Update to v5.7

I must be blind then because i saw it as v5. Well its fixed now.

**Comment by L337Hun73r** [comment]
![image](https://github.com/user-attachments/assets/7e2a9e42-88cb-430f-8d42-430c817a2904)
Hate to necro this but I can't download from a "bunkr.fi" link...

**Comment by L337Hun73r** [comment]
![image](https://github.com/user-attachments/assets/d21e1bd8-a8c7-499d-8659-fefa5a4cff5e)


ALSO I got this when I opened the program after it (Yea, I know. Manly McBeefington is not as funny as I think)
