### ISSUE TITLE
[FEATURE] download from all your coomer favorites at once

### ISSUE THREAD

**Issue by pdobrien** [jbsparrow/CyberDropDownloader#224]
**Is your feature request related to a problem? Please describe.**
I have to manually download from each coomer URL whenever they are updated

**Describe the solution you'd like**
I would like to be able to provide my coomer login to cyberdrop-dl and have it download from all creators I've favorited

**Comment by jbsparrow** [comment]
This seems like a nice feature, I'll take a look at implementing it later today.
