### ISSUE TITLE
Pip doesn't update anymore?

### ISSUE THREAD

**Issue by Aer3x** [jbsparrow/CyberDropDownloader#228]
After V5.6.54 

`pip install --upgrade cyberdrop-dl-patched`
isnt't updating anymore/ doesn't find a new release.

**Comment by Aer3x** [comment]
changed python 13.0 to 12.7 and its downloading again..
was working before with python 13.0 without errors but stopped updating because not supported i guess.

**Comment by NTFSvolume** [comment]
> changed python 13.0 to 12.7 and its downloading again.. was working before with python 13.0 without errors but stopped updating because not supported i guess.

Correct. New releases explicitly do not support 3.13 cause some dependencies do not have wheels available for it yet. PIP only installs the latest supported release.
