### ISSUE TITLE
[BUG] All downloads being "skipped by config"

### ISSUE THREAD

**Issue by c0d3m0nky** [jbsparrow/CyberDropDownloader#234]
Everything is being "Skipped by config" with coomer host. It seems to have started sometime between 10/27 and 10/31

Config:
`Download_Options:
  block_download_sub_folders: false
  disable_download_attempt_limit: false
  disable_file_timestamps: false
  include_album_id_in_folder_name: false
  include_thread_id_in_folder_name: false
  remove_domains_from_folder_names: false
  remove_generated_id_from_filenames: false
  scrape_single_forum_post: false
  separate_posts: true
  skip_download_mark_completed: false
  skip_referer_seen_before: false
File_Size_Limits:
  maximum_image_size: 0
  maximum_other_size: 0
  maximum_video_size: 0
  minimum_image_size: 0
  minimum_other_size: 0
  minimum_video_size: 20971520
Files:
  download_folder: Downloads
  input_file: coomer.txt
Ignore_Options:
  exclude_audio: true
  exclude_images: false
  exclude_other: false
  exclude_videos: false
  ignore_coomer_ads: false
  only_hosts:
  - coomer
  - kemono
  skip_hosts: []
Logs:
  download_error_urls_filename: coomer_Download_Error_URLs.csv
  last_forum_post_filename: coomer_Last_Scraped_Forum_Posts.txt
  log_folder: logs
  main_log_filename: coomer.log
  rotate_logs: false
  scrape_error_urls_filename: coomer_Scrape_Error_URLs.csv
  unsupported_urls_filename: coomer_Unsupported_URLs.txt
  webhook_url: ''
Runtime_Options:
  console_log_level: 100
  delete_partial_files: false
  ignore_history: false
  jdownloader_autostart: false
  jdownloader_download_dir: null
  jdownloader_whitelist: []
  log_level: 10
  send_unsupported_to_jdownloader: false
  skip_check_for_empty_folders: false
  skip_check_for_partial_files: false
  update_last_forum_post: false
Sorting:
  scan_folder: None
  sort_cdl_only: true
  sort_downloads: false
  sort_folder: Downloads/Cyberdrop-DL Sorted Downloads
  sort_incremementer_format: ' ({i})'
  sorted_audio: '{sort_dir}/{base_dir}/Audio/{filename}{ext}'
  sorted_image: '{sort_dir}/{base_dir}/Images/{filename}{ext}'
  sorted_other: '{sort_dir}/{base_dir}/Other/{filename}{ext}'
  sorted_video: '{sort_dir}/{base_dir}/Videos/{filename}{ext}'
`

Example url: https://coomer.su/onlyfans/user/lilycherry666

**Setup Information**
 - OS: Ubuntu 22.04.2 LTS (Docker container)
 - Cyberdrop Downloader Version 5.7.0

**Downloader.log file**
[coomer.log](https://github.com/user-attachments/files/17612980/coomer.log)

**Comment by c0d3m0nky** [comment]
Saw that 5.7.1rc0 got pushed earlier today so I tried it but still got the same issue

**Comment by NTFSvolume** [comment]
> Saw that 5.7.1rc0 got pushed earlier today so I tried it but still got the same issue
> 
> If it helps troubleshoot, if I remove "kemono" leaving only "coomer" it works with 5.7.1rc0

Can you please share the logs of 5.7.1rc0? Now it should at least log why are they being skipped

**Comment by c0d3m0nky** [comment]
https://coomer.su/onlyfans/user/mollymontana
[coomer.log](https://github.com/user-attachments/files/17641629/coomer.log)

**Comment by NTFSvolume** [comment]
> https://coomer.su/onlyfans/user/mollymontana [coomer.log](https://github.com/user-attachments/files/17641629/coomer.log)

That log is from 5.7.0, not 5.7.1rc0

**Comment by c0d3m0nky** [comment]
Ok, I dunno how that happened, I def ran `pip3 install --force-reinstall cyberdrop-dl-patched==5.7.1rc0` before that run

Anyway, it's def installed now, and it's all scrape failures

[coomer.log](https://github.com/user-attachments/files/17656115/coomer.log)
