### ISSUE TITLE
Unable to run : Code 65001

### ISSUE THREAD

**Issue by deadbeatdandylyon** [jbsparrow/CyberDropDownloader#248]
I don't know if anyone can help me as I know this is probably not a specific issue to cyberdrop

I have 3 versions of Python installed on my system 3.11 and 3.13 and 3.10, When I try to run the script for Cyberdrop its giving the following message

![image](https://github.com/user-attachments/assets/7b357ef6-772f-4598-b21c-7b697dfc17e2)

is there any way to make it so that it can run as I do have both of those versions of python installed if so how?

**Comment by NTFSvolume** [comment]
1. Open a terminal and run `py --list-paths`. It will show you the paths of your installed python versions. The output will be something like this:

```cmd
 -V:3.13 *        C:\Program Files\Python313\python.exe
 -V:3.11          C:\Program Files\Python311\python.exe
```
2. Copy the path of python `3.11` and open the startup script of Cyberdrop-DL ( the `.bat` file) in notepad 
3. Paste the path inside the `PYTHON` variable at the top. This will force the use of python `3.11`

#### Before:

```shell
rem User defined variables

set "PYTHON="
set "VENV_DIR="
set "COMMANDLINE_ARGS="
```

#### After:

```shell
rem User defined variables

set "PYTHON=C:\Program Files\Python311\python.exe"
set "VENV_DIR="
set "COMMANDLINE_ARGS="
```

**Comment by deadbeatdandylyon** [comment]
I did the following as you assisted with and getting the following message 

![image](https://github.com/user-attachments/assets/8160cd4b-4d34-4422-9768-a1b7acd6b3ac)


![image](https://github.com/user-attachments/assets/624abeb2-8458-4544-b730-a0ba05596b3d)

After when I press Enter it just closes the script

**Comment by NTFSvolume** [comment]
There was a old `venv` already created. Delete any `.venv`  or `venv` folder in the same path as the script. You may need to enable `view hidden files` to delete it

**Comment by deadbeatdandylyon** [comment]
Thank you very much, yes after deleting the venv folder it worked perfectly, 

Thank you for your assistance and also explaining it in easy to follow instructions!
