### ISSUE TITLE
[FEATURE] Get DDoS-Guard cookie credentials from flaresolverr

### ISSUE THREAD

**Issue by baccccccc** [jbsparrow/CyberDropDownloader#250]
I encountered an URL on `saint2` which is protected by DDoS-Guard.

Download_Error_URLs.csv
```
https://cold1.saint2.cr/videos/1e14058ca9b8ed77c1189b61f95dafd0.mp4 ,DDoS-Guard detected ,https://cold1.saint2.cr/videos/1e14058ca9b8ed77c1189b61f95dafd0.mp4 
```

downloader.log
```
[11/08/24 09:15:33] INFO     Download starting: https://cold1.saint2.cr/videos/1e14058ca9b8ed77c1189b61f95dafd0.mp4                                                                                                             utilities.py:107
                    ERROR    Download failed: https://cold1.saint2.cr/videos/1e14058ca9b8ed77c1189b61f95dafd0.mp4 with error: DDoS-Guard detected                                                                               utilities.py:107
                    INFO     Download finished: https://cold1.saint2.cr/videos/1e14058ca9b8ed77c1189b61f95dafd0.mp4                                                                                                             utilities.py:107
```

I have FlareSolver configured, and normally it does pretty well dealing with DDoS-Guard. But here, I don't even see the request going to FlareSolver.

To me, it looks like currently CDL only uses FlareSolver when scraping, but not when downloading.

**Comment by NTFSvolume** [comment]
Flaresolverr does not support binary payload requests. They used to, for files up to 20MB, but even that was removed.

This would require making a GET request to the base host with flaresolverr, saving the cookies instead of the response, apply the cookies to the client session and them making the download request again. This is not trivial cause they host may just reject requests if they do not have a path or query. Probably doable but not really worth implementing

Better to apply an universal cookies management solution so the user can inject the cookies themself before starting CDL

**Comment by baccccccc** [comment]
I don't disagree. If I could leverage cookies obtained from FS (or other tools) into CDL that would probably solve the problem. Sounds like it would require a bunch of manual work, but so far, there are only singular cases where DDG prevents me from downloading files, so it might be enough.

**Comment by NTFSvolume** [comment]
We’ve had a branch with a working implementation of this for a while, but it hasn’t been included in a public release yet. 

The process it fully automatic from the UI. The user just needs to choose the browser from which they want to import the cookies from. It's similar to the current implementation of the `import cookies from browser` option but it will import _all_ cookies (including DDoS Guard ones) from any supported site, not just login credentials from forums.

User will also be able to add the cookies manually as a file to CDL's `AppData` folder, if they want to.

However, I do see value in getting the cookies from flaresolverr. May be good for some edge cases. Will leave this issue open so it can be addressed some time in the future
