### ISSUE TITLE
[BUG] Bunkr scraping timeout errors

### ISSUE THREAD

**Issue by vajdao** [jbsparrow/CyberDropDownloader#295]
I'm having constant bunkr timeouts no matter what kind of album or direct links I'm trying to download, most of them get timed out.

**Setup Information**
**cyberdrop-dl 5.7.1**

Operating System: openSUSE Tumbleweed 20241114
KDE Plasma Version: 6.2.3
KDE Frameworks Version: 6.8.0
Qt Version: 6.8.0
Kernel Version: 6.11.7-1-default (64-bit)
Graphics Platform: X11
Processors: 4 × Intel® Core™ i5-6500 CPU @ 3.20GHz
Memory: 15.6 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2
Manufacturer: MSI
Product Name: MS-7972
System Version: 2.0

I've found there was some similiar issue 3weeks ago at #204 

**Downloader.log file**
[downloader.log](https://github.com/user-attachments/files/17786760/downloader.log)

Ps: I've set the timeout to 1sec for debugging purpose to quickly gather the links, but when it was set on default 15s/300s it was the same results.

Just a thought edit: I'm not sure how to trace it back, but seeing the [bunkrr_crawler.py](https://github.com/jbsparrow/CyberDropDownloader/blob/35132e34e08d6cf89e47ce93556b3d649b1d94fb/cyberdrop_dl/scraper/crawlers/bunkrr_crawler.py#L23) source code, is the script really trying all the combinations as intended? Because it seems it stops at `milkshake` in my case, and doesn't seem to advance further in order to retry with the other domain combinations perhaps? (but really just a quick thought/idea)
```py
CDN_POSSIBILITIES = re.compile(
    r"^(?:(?:(?:media-files|cdn|c|pizza|cdn-burger|cdn-nugget|burger|taquito|pizza|fries|meatballs|milkshake|kebab|nachos|ramen|wiener)[0-9]{0,2})|(?:(?:big-taco-|cdn-pizza|cdn-meatballs|cdn-milkshake|i.kebab|i.fries|i-nugget|i-milkshake|i-nachos|i-ramen|i-wiener)[0-9]{0,2}(?:redir)?))\.bunkr?\.[a-z]{2,3}$")

```

**Comment by NTFSvolume** [comment]
All the timeout errors are from the milkshake server.

The server is overloaded and can not handle new requests. Trying to download the files manually gives the same result. Nothing CDL can do about it, just wait until they upgrade the server or move the files to a new one.

> Just a thought edit: I'm not sure how to trace it back, but seeing the [bunkrr_crawler.py](https://github.com/jbsparrow/CyberDropDownloader/blob/35132e34e08d6cf89e47ce93556b3d649b1d94fb/cyberdrop_dl/scraper/crawlers/bunkrr_crawler.py#L23) source code, is the script really trying all the combinations as intended? Because it seems it stops at `milkshake` in my case, and doesn't seem to advance further in order to retry with the other domain combinations perhaps? (but really just a quick thought/idea)
> 
> ```python
> CDN_POSSIBILITIES = re.compile(
>     r"^(?:(?:(?:media-files|cdn|c|pizza|cdn-burger|cdn-nugget|burger|taquito|pizza|fries|meatballs|milkshake|kebab|nachos|ramen|wiener)[0-9]{0,2})|(?:(?:big-taco-|cdn-pizza|cdn-meatballs|cdn-milkshake|i.kebab|i.fries|i-nugget|i-milkshake|i-nachos|i-ramen|i-wiener)[0-9]{0,2}(?:redir)?))\.bunkr?\.[a-z]{2,3}$")
> ```

The files are on one single server at any given time, not on all of them. CDL just checks which one the file is hosted on.
