### ISSUE TITLE
[BUG]UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 253: character maps to <undefined>

### ISSUE THREAD

**Issue by Aliaksandr3by** [jbsparrow/CyberDropDownloader#300]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 253: character maps to <undefined>

![{BBD5EA69-389B-4FB8-A82C-16806E290BB2}](https://github.com/user-attachments/assets/1346ff86-c06e-47d6-85ca-abd605e790e4)

windows 11 64 23h2

**Comment by jbsparrow** [comment]
Please attach your log and URLs file.

**Comment by NTFSvolume** [comment]
Disable `update_last_forum_post` in your config.  You cannot use `update_last_forum_post` if your input is `html`code.
