### ISSUE TITLE
[BUG] AttributeError: 'NoneType' object has no attribute 'text'  

### ISSUE THREAD

**Issue by just-a-guy-cloud** [jbsparrow/CyberDropDownloader#320]
**Describe the bug**
Seems that coomer.su links are not downloading for me. I tried removing all files and reinstalling but still getting the error with coomer.su sites. 

**To Help Reproduce**
Steps to help reproduce the behavior:
Have a coomer link in your URLs.txt
Select the profile and attempt to download the coomer.su profile.
The scrape fails for me with the error in logs 
```
ERROR    Scrape Failed: https://coomer.su/onlyfans/user/bunniepremium ('NoneType' object has no attribute 'text')     
```

**Screenshots**

**Setup Information**
 - OS: Windows 11 Python 3.11.6
 - Cyberdrop Downloader Version # 5.7.2

**Downloader.log file**

[downloader.log](https://github.com/user-attachments/files/17912592/downloader.log)

**Additional context**

**Comment by Kenneth-Rosenstroem** [comment]
Yep. The last update broke coomer support. Same problem.
[Scrape_Error_URLs.csv](https://github.com/user-attachments/files/17913015/Scrape_Error_URLs.csv)
[downloader.log](https://github.com/user-attachments/files/17913016/downloader.log)

**Comment by crazydavebacon** [comment]
same here 


[downloader.log](https://github.com/user-attachments/files/17922682/downloader.log)

**Comment by jbsparrow** [comment]
Will implement a fix to this in a few hours.

**Comment by baccccccc** [comment]
> Will implement a fix to this in a few hours.

Thank you! I was hesitant to report the same because I'm using Python 3.13 and I am too lazy to attempt a repro with a supported version :) Looking forward for the fix!

**Comment by electricfish1** [comment]
Same issue here. Looks like Coomer may have made some changes on there end where the body of the page is now lazy loaded.

**Comment by electricfish1** [comment]
This resolves the issue:

Updating the `get_user_str_from_profile`  function in scraper/crawlers/coomer_crawler.py

```python
async def get_user_str_from_profile(self, scrape_item: ScrapeItem) -> str:
        """Gets the user string from a scrape item"""
        service, user = await self.get_service_and_user(scrape_item)
        api_call = self.api_url / service / "user" / user / "profile"
        async with self.request_limiter:
            user_data = await self.client.get_json(self.domain, api_call)
            return user_data['name']
```

**Comment by crazydavebacon** [comment]
DO we have an ETA on this? Yesterday we were a few hours away from a fix. Still hasn't has an update.
