### ISSUE TITLE
[BUG] Fresh install, something is very wrong

### ISSUE THREAD

**Issue by L337Hun73r** [jbsparrow/CyberDropDownloader#357]
Haven't been using the downloader since some time and needed to use it now. Decided to download the newest one on a fresh install. Did. Started first time, let the files download and than I put the download location and created url txt. Put a bunkr.fi link in the URLs file, started and this happened:

![image](https://github.com/user-attachments/assets/6f5ebddc-9778-493c-80e7-188b9a0390ea)

Necro'ed [[Bunkr scrape issue](https://github.com/jbsparrow/CyberDropDownloader/issues/219#top)
**#219**](https://github.com/jbsparrow/CyberDropDownloader/issues/219#top) but after my message, I wanted to try again and this happened:

![image](https://github.com/user-attachments/assets/07f40555-a4f1-45a2-9160-72f8f3307c9b)

So it shows ".py" files corrupted (I think), and says the URLs.txt file is not existent but it is there. Don't really know what to do.

Sorry if these are unnecessary screenshots but I don't know what might help, so here goes:
- My "venv\Scripts" folder does not contain a "cyberdropdl.exe" file, where "__main__.py" could've been found.

- My line 241 in "venv\Lib\site-packages\cyberdrop_dl\main.py" is this:
![image](https://github.com/user-attachments/assets/d4ee0357-f76c-4629-ad86-a01e7d01b9e5)

- My line 48 in "venv\Lib\site-packages\cyberdrop_dl\main.py" is this:
![image](https://github.com/user-attachments/assets/77562a47-a8ed-4856-aea8-b7b48c14c1c8)

- My line 82 in "venv\Lib\site-packages\cyberdrop_dl\managers\manager.py" is this:
![image](https://github.com/user-attachments/assets/676b98be-cc28-43ea-94ae-4bc1038def22)

- My line 103 in "venv\Lib\site-packages\cyberdrop_dl\managers\path_manager.py" is this:
![image](https://github.com/user-attachments/assets/739e0336-ee13-411e-9320-0f91f561f86d)

- My line 1108 in "AppData\Local\Programs\Python\Python311\Lib\pathlib.py" is this:
![image](https://github.com/user-attachments/assets/39a8b4ca-0524-4652-8231-41845fa7d185)

**Setup Information**
 - OS: Windows 10 Pro, probably very latest update.
 - Cyberdrop Downloader Version absolutely LATEST, for I just downloaded it

**Downloader.log file**
[downloader.log](https://github.com/user-attachments/files/18051677/downloader.log)

**Additional context**
Got no idea how to use Python, so if there were a "pip update or something something", I need **_clear_** instructions :")

**Comment by NTFSvolume** [comment]
Don't create the `URLs.txt` file manually, use the option in the program to add links or change its path.

Or download the zip again but extract it to a different location.

The path you are using has special characters (the `ı` in `kısayol`). If you try to manually set a path for the `URLs.txt`, it won't work cause windows will corrupt the path before passing it to the program.

**Comment by L337Hun73r** [comment]
Changed name of the folder, installed fresh. Same zero result came at the first try. Second try resulted in this error:
![image](https://github.com/user-attachments/assets/23069093-0510-4a0d-8022-504b0d24a78a)

Downloader.log file:
[downloader.log](https://github.com/user-attachments/files/18053480/downloader.log)

**_(Sorry for late reply. Living in different timezone)_**

**Comment by NTFSvolume** [comment]
The value of `input_file` is invalid. It should be a file, not a folder

```json
"Files": {                                                                                                                                                                                                     
    "download_folder": "D:\\yedekler\\yeni cyberdrop dl",                                                                                                                                                      
     "input_file": "C:\\Users\\Manly McBeefington\\Desktop\\ksayol\\Cyberdrop-DL v5"                                                                                                                            
    }
```

Delete any `.venv`, `venv` and `AppData` folder. It's better if you just delete everything. Keep just the start script and run it again. CDL will recreate the default values.

**Comment by L337Hun73r** [comment]
I wrote in "Cyberdrop-DL v5\URLs.txt" in the configuration edit option but somehow it's just not working when I do it. So anyway I listened to your advice, deleted everything and installed fresh. Changed absolutely nothing and it worked (Currently downloading the link's contents). So I guess I won't be changing the URLs file location and even the download folder location just in case. Nothing so big for me but mildly annoying. Thanks for the help!

**Comment by L337Hun73r** [comment]
Lol, sorry... 403 forbidden "error" came out for files. Only 15 out of 46 files downloaded from the link.

[downloader.log](https://github.com/user-attachments/files/18053724/downloader.log)

All errored links have "milkshake" in their names
![image](https://github.com/user-attachments/assets/391de4d7-98ed-4ba9-85b3-bb8b111eac15)

**Comment by NTFSvolume** [comment]
The server is under maintenance: https://status.bunkr.ru/

![Screenshot_20241208_144521_Firefox](https://github.com/user-attachments/assets/a9f4ac3e-df45-49eb-8e92-029d88504603)

**Comment by L337Hun73r** [comment]
Thanks again for the help!
