### ISSUE TITLE
Still unable to scrape gofile links

### ISSUE THREAD

**Issue by deadbeatdandylyon** [jbsparrow/CyberDropDownloader#364]
As of today 9pm 12/11/2024 still unable to scrape gofile links. 

The troubleshooting steps that I have performed so far is.

1) First deleted the cache folder and then attempted to scrape - still unable to

2) Deleted the whole cyberdrop folder > restarted computer > redownloaded the zip > attempted to download the gofile link again > still unable to 

3) Tested multiple gofile links and all are giving off the same issue. 

Here is the updated log file: https://hastebin.com/share/dinazexeza.rust

At this point not sure what else to test. 

I do not have any VPN software, Do not have any antivirus software.

**Comment by NTFSvolume** [comment]
This was already fixed by #356 but a new version has not been released.

The fix will be included in v6.0

**Comment by deadbeatdandylyon** [comment]
Oh okay I didn't see that part where it says a new version, i thought it was fixed in the current version, my apologies
