### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'aiolimiter.compat'

### ISSUE THREAD

**Issue by dexter-amico** [jbsparrow/CyberDropDownloader#374]
### I have taken steps to troubleshoot my issue first

- [X] I'm using the latest version of `cyberdrop-dl-patched`
- [X] I’ve read the wiki and my issue isn’t already covered.
- [X] I’ve checked existing issues to ensure this hasn’t been reported already.

### Describe the bug

After a fresh install trying to run Cyberdrop gives an error based on a missing module named 'aiolimiter.compat', this module is part from aiolimiter lib and was removed from release 1.1.1 onwards.

### Desired result

Running cyberdrop without a module missing exception.

### Steps to help reproduce the behavior

1. Uninstall previous installed version of cyberdrop
2. Do a fresh install using pip accordingly to wiki instructions
3. Try to run cyberdrop

### Relevant logs

```
Microsoft Windows [versão 10.0.19045.5247]
(c) Microsoft Corporation. Todos os direitos reservados.

C:\Users\rafae>cyberdrop-dl
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python\Scripts\cyberdrop-dl.exe\__main__.py", line 4, in <module>
  File "C:\Python\Lib\site-packages\cyberdrop_dl\main.py", line 18, in <module>
    from cyberdrop_dl.managers.manager import Manager
  File "C:\Python\Lib\site-packages\cyberdrop_dl\managers\manager.py", line 12, in <module>
    from cyberdrop_dl.managers.client_manager import ClientManager
  File "C:\Python\Lib\site-packages\cyberdrop_dl\managers\client_manager.py", line 19, in <module>
    from cyberdrop_dl.managers.leaky import LeakyBucket
  File "C:\Python\Lib\site-packages\cyberdrop_dl\managers\leaky.py", line 8, in <module>
    from aiolimiter.compat import wait_for
ModuleNotFoundError: No module named 'aiolimiter.compat'
```

### Operating system/environment

Windows 10

### Python Version

3.12.8

### Cyberdrop-DL version

5.7.2

### Links, references, and/or additional comments?

One possible hotfix solution is to force the use of release 1.1.0 of aiolimiter lib. But a long term solution must be sought since this old release of aiolimiter must become inaccessible anytime soon.

**Comment by NTFSvolume** [comment]
- Fixed in v6.0.0
- Fixed by #359
