### ISSUE TITLE
[BUG] JPG5 coming back to no file extentions error on every file

### ISSUE THREAD

**Issue by crazydavebacon** [jbsparrow/CyberDropDownloader#387]
### I have taken steps to troubleshoot my issue first

- [X] I'm using the latest version of `cyberdrop-dl-patched`
- [X] I’ve read the wiki and my issue isn’t already covered.
- [X] I’ve checked existing issues to ensure this hasn’t been reported already.

### Describe the bug

Jpg5 is coming back to no file extension error recently. Nothing will download from them anymore. 

### Desired result

be able to download from JPG5 again. 

### Steps to help reproduce the behavior

https://jpg4.su/yamato_69
https://jpg5.su/yamato_69

just a link with a lot of pics that wont work, alongside any jpg5 link

### Relevant logs

[downloader.log](https://github.com/user-attachments/files/18219098/downloader.log)
[downloader.log](https://github.com/user-attachments/files/18219104/downloader.log)

### Operating system/environment

Windows 10 latest version

### Python Version

latest

### Cyberdrop-DL version

5.7.2.post4

### Links, references, and/or additional comments?

I did both the jpg4 link and jpg5 link and both do the same. Both logs are in the lo list

**Comment by NTFSvolume** [comment]
- Fixed in v6.0.0
- Fixed by #354, commit [f3b410f](https://github.com/jbsparrow/CyberDropDownloader/pull/354/commits/f3b410f8310ddbd6e4c964b44ee1dcb688a5f56c)
